[versions]

proguard-version = "7.6.0"
junit-bom-version = "5.10.0"
kotlin-version = "2.0.21"


[libraries]

com-guardsquare-proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard-version" }
org-junit-junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom-version" }
org-junit-jupiter-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-version" }


[plugins]

org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
java = { id = "java" }
